export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";

export const PROFILE_EDITING = "PROFILE_EDITING";
export const SAVE_PROFILE_CHANGES = "SAVE_PROFILE_CHANGES";

export const SET_EDIT_JOB = "SET_EDIT_JOB";
