export const DISPLAY_ALERT = "SHOW_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";

export const PROFILE_EDITING = "PROFILE_EDITING";
export const SAVE_PROFILE_CHANGES = "SAVE_PROFILE_CHANGES";

export const REGISTER_USER_BEGIN = "REGISTER_USER_BEGIN";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";

export const LOGIN_USER_BEGIN = "LOGIN_USER_BEGIN";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export const LOGOUT_USER = "LOGOUT_USER";

export const UPDATE_USER_BEGIN = "UPDATE_USER_BEGIN";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";

export const GET_INPUT_VALUE = "GET_INPUT_VALUE";
export const CLEAR_VALUES = "CLEAR_VALUES";
export const CLEAR_SEARCHING_FILTERS = "CLEAR_SEARCHING_FILTERS";

export const ADD_JOB_BEGIN = "ADD_JOB_BEGIN";
export const ADD_JOB_SUCCESS = "ADD_JOB_SUCCESS";
export const ADD_JOB_ERROR = "ADD_JOB_ERROR";

export const GET_JOBS_BEGIN = "GET_JOBS_BEGIN";
export const GET_JOBS_SUCCESS = "GET_JOBS_SUCCESS";

export const SET_EDIT_JOB = "SET_EDIT_JOB";
export const EDIT_JOB_BEGIN = "EDIT_JOB_BEGIN";
export const EDIT_JOB_SUCCESS = "EDIT_JOB_SUCCESS";
export const EDIT_JOB_ERROR = "EDIT_JOB_ERROR";

export const DELETE_JOB = "DELETE_JOB";

export const CHANGE_PAGE = "CHANGE_PAGE";
export const GET_VISIBLE_PAGES = "GET_VISIBLE_PAGES";

export const GET_STATS_BEGIN = "GET_STATS_BEGIN";
export const GET_STATS_SUCCESS = "GET_STATS_SUCCESS";

export const GET_CURRENT_USER_BEGIN = "GET_CURRENT_USER_BEGIN";
export const GET_CURRENT_USER_SUCCESS = "GET_CURRENT_USER_SUCCESS";
